### ISSUE TITLE
issue with update option in pwsafecli.py

### ISSUE THREAD

**Issue by makiredd** [ronys/pypwsafe#13]
Hi,

When I try to update .psafe3 file using below command
$python pwsafecli.py get --uuid "****" --password "****"  --file OperationsSafe2018.psafe3 2>updatePwsafe.err
then OperationsSafe2018.psafe3  got corrupted and unable to get record again.

Please help. Thank you

**Comment by Bastian82** [comment]
Hmm,
I look at it, and i faced completly different issue. The functon responsible for updating is missing. There is no `add_or_update_records` anywhere in the code?

`Traceback (most recent call last):
  File "/Users/krzysztof.grzempa/Projects/pypwsafe/pwsafecli/pwsafecli.py", line 422, in <module>
    main(options)
  File "/Users/krzysztof.grzempa/Projects/pypwsafe/pwsafecli/pwsafecli.py", line 404, in main
    func(options)
  File "/Users/krzysztof.grzempa/Projects/pypwsafe/pwsafecli/pwsafecli.py", line 283, in update_action
    add_or_update_records(safe, records[0], options)
NameError: global name 'add_or_update_records' is not defined`

Is it ever been created ?
